Dev
Yar-ua/auction pull request #3
Opened 2018-05-24 13:06 UTC by Yar-ua

Added and tested Devise_token_auth. Created Lots (lots must be improved). Created tests for auth and lots

2018-05-28 11:31 UTC, an-tk requested changes

2018-05-28 11:31 UTC, an-tk commented on README.md
> +- ActionMailer must be initialised for test auth comfirmation by email. API configured to send the confirmation e-mail via SMTP to localhost:1025, mailcatcher will catch email in development and test
а как это будет работать на каких то  CI тулах?

2018-05-28 11:31 UTC, an-tk commented on app/controllers/lots_controller.rb
> +  def send_response(status, data)
если поменять местами data и status, то можно задать дефолтный статус send_response(data, status=:ok) и пользоваться методом send_response(data), без второго аттрибута

2018-05-28 11:31 UTC, an-tk commented on app/controllers/lots_controller.rb
> +      send_response(200, @lots)
пагинацию на потом оставляем или сейчас добавим?

2018-05-28 11:31 UTC, an-tk commented on app/controllers/lots_controller.rb
> +  def send_response(status, data)
это похоже на на метод для ApplicationController а не только для LotsController

2018-05-28 11:31 UTC, an-tk commented on app/models/lot.rb
> +  validates :current_price, :estimated_price, numericality: { only_integer: false, message: 'Value must be digit' }
возможно эти 2 валидации можно записать в одну строчку

2018-05-28 11:31 UTC, an-tk commented on app/models/lot.rb
> +  def valid_lot_times
для этого нужны тесты

2018-05-28 11:31 UTC, an-tk commented on app/models/lot.rb
> +  validate :valid_lot_times
похоже что validates_datetime предоставляет валидации того что ты делаешь своим методом. проверь пжлста,  возможно стоит заюзать его, раз он уже установлен

2018-05-28 11:31 UTC, an-tk commented on config/routes.rb
> +  get '/mylots' => 'lots#mylots'
почему этот роут не в неймспейсе лотов? было бы логично

2018-05-28 11:31 UTC, an-tk commented on db/migrate/20180520145150_create_lots.rb
> +      t.string :description, :default => "null"
это по дефолту строка "null"? странно.

2018-05-28 11:31 UTC, an-tk commented on db/seeds.rb
> +User.find_or_create_by! email: 'hulk@gmail.com' do |user|
давай использовать для этого FactoryBot
```
users = create_list(:user, 10)
users.map do |u|
create_list(:lot, 5, user: u)
end
```
как то так

2018-05-28 11:31 UTC, an-tk commented on db/seeds.rb
> +
вообще обычно сиды делаются так: все удаляется кроме table == 'schema_migrations'
потом все создается

2018-05-28 11:31 UTC, an-tk commented on spec/controllers/lots_controller_spec.rb
> +      @current_user = FactoryBot.create(:user)
spec/spec_helper.rb
 
config.include FactoryGirl::Syntax::Methods

и можно будет просто create(:user)

2018-05-28 11:31 UTC, an-tk commented on spec/factories/user.rb
> +    first_name Faker::Name.first_name
юзеры с разными именами создаются?

2018-05-28 11:31 UTC, an-tk commented on spec/models/lot_spec.rb
> +    it { should respond_to(:title)}
it { is_expected.to ... }

давай либо expect либо should

2018-05-28 22:04 UTC, Yar-ua commented on app/controllers/lots_controller.rb
> +  def send_response(status, data)
можно, сделаю

2018-05-28 22:06 UTC, Yar-ua commented on app/controllers/lots_controller.rb
> +      send_response(200, @lots)
сейчас, не успел добавить

2018-05-28 22:06 UTC, Yar-ua commented on app/models/lot.rb
> +  def valid_lot_times
ок, добавлю

2018-05-28 22:10 UTC, Yar-ua commented on db/migrate/20180520145150_create_lots.rb
> +      t.string :description, :default => "null"
а как правильно делать, просто пустой строкой типа '' ?
По заданию у меня есть параметры required, которые обязательно должны быть. Картинка  и description вроде как необязательные параметры ...

2018-05-28 22:11 UTC, Yar-ua commented on db/seeds.rb
> +User.find_or_create_by! email: 'hulk@gmail.com' do |user|
ок, изменю

2018-05-28 22:12 UTC, Yar-ua commented on spec/controllers/lots_controller_spec.rb
> +      @current_user = FactoryBot.create(:user)
ок, попробую сделать

2018-05-28 22:16 UTC, Yar-ua commented on spec/factories/user.rb
> +    first_name Faker::Name.first_name
да

2018-05-28 22:17 UTC, Yar-ua commented on spec/models/lot_spec.rb
> +    it { should respond_to(:title)}
ок

2018-05-28 22:19 UTC, Yar-ua commented on app/models/lot.rb
> +  validate :valid_lot_times
да, можно использовать валидацию типа
validates_datetime :finish_time, :after => :start_time

2018-05-28 22:21 UTC, Yar-ua commented on app/controllers/lots_controller.rb
> +  def send_response(status, data)
в принципе да, для orders тоже буду юзать response такого плана...

2018-05-30 20:08 UTC, Yar-ua commented on README.md
> +- ActionMailer must be initialised for test auth comfirmation by email. API configured to send the confirmation e-mail via SMTP to localhost:1025, mailcatcher will catch email in development and test
убрал обязательный запуск mailcatcher

2018-05-30 20:08 UTC, Yar-ua commented on app/controllers/lots_controller.rb
> +  def send_response(status, data)
сделано

2018-05-30 20:09 UTC, Yar-ua commented on app/controllers/lots_controller.rb
> +      send_response(200, @lots)
добавил пагинацию по 10 лотов

2018-05-30 20:09 UTC, Yar-ua commented on app/controllers/lots_controller.rb
> +  def send_response(status, data)
перенес в ApplicationController

2018-05-30 20:11 UTC, Yar-ua commented on app/models/lot.rb
> +  validates :current_price, :estimated_price, numericality: { only_integer: false, message: 'Value must be digit' }
по моему нет... тут в одной строке проверяется наличие какого дибо значения, а во второй уже проверка на то что значение число

2018-05-30 20:11 UTC, Yar-ua commented on app/models/lot.rb
> +  validate :valid_lot_times
сделал валидацию методами validates_datetime

2018-05-30 20:12 UTC, Yar-ua commented on app/models/lot.rb
> +  def valid_lot_times
этот метод удален (см. следующий комментарий, валидация будет методами гема)

2018-05-30 20:13 UTC, Yar-ua commented on config/routes.rb
> +  get '/mylots' => 'lots#mylots'
перенес в /lots/mylots

2018-05-30 20:13 UTC, Yar-ua commented on db/migrate/20180520145150_create_lots.rb
> +      t.string :description, :default => "null"
сделал по дефолту пустой строкой

2018-05-30 20:14 UTC, Yar-ua commented on db/seeds.rb
> +User.find_or_create_by! email: 'hulk@gmail.com' do |user|
сделал через FactoryBot

2018-05-30 20:14 UTC, Yar-ua commented on spec/factories/user.rb
> +    first_name Faker::Name.first_name
нет, создавались с одним именем, переделал чтобы создавались с разными

2018-05-30 20:15 UTC, Yar-ua commented on spec/models/lot_spec.rb
> +    it { should respond_to(:title)}
сделал все через expect

2018-06-06 19:42 UTC, merged